export const partijen = [
"Van Vliet",
"Partij voor de Vrijheid",
"ChristenUnie",
"Groep van Oudenallen",
"Groep De Jong",
"50PLUS",
"Democratisch Politiek Keerpunt",
"Socialistische Partij",
"Brinkman",
"50PLUS/Klein",
"Monasch",
"Staatkundig Gereformeerde Partij",
"Leefbaar Nederland",
"Partij voor de Dieren",
"Groep Eerdmans-van Schijndel",
"Lijst Pim Fortuyn",
"Groep Nawijn",
"DENK",
"Klein",
"50PLUS/Baay-Timmerman",
"Groep Bontes/Van Klaveren",
"Groep Lazrak",
]


export const personen = [
"Sjoera Dikkers",
"Fredrik Teeven",
"Liesbeth Tongeren",
"Selcuk Öztürk",
"Martinus Hendricus Petrus Dam",
"Keklik Yücel",
"H. Backx",
"Gideon Markuszower",
"Foort Oosten van",
"Mevrouw J. Calkoen-Nauta",
"Margot Kraneveldt-van der Veen",
"Helma Neppérus",
"Raymond Knops",
"H. Andela",
"Martine Baay",
"Lilianne Ploumen",
"Antonius Adrianus Gerardus Maria Raak",
"De heer R.A.C. Hoksbergen",
"Antoine Pierre Cornelis Dijck",
"Mark Rutte",
"Jaap Hanekamp",
"E. Ugurlu",
"Sanne Van Eerden",
"Machiel Graaf de",
"Jet Bussemaker",
"André Postema",
]



export const moties = [
"Mariene Strategie voor het Nederlandse deel van de Noordzee",
"Vaststelling van de begrotingsstaten van het Ministerie van Economische Zaken (XIII) voor het jaar 2009",
"Zorg rond zwangerschap en geboorte",
"Wijziging van enkele belastingwetten en enige andere wetten (Fiscale verzamelwet 2015)",
"Maatregelen verkeersveiligheid",
"Derde Structuurschema Elektriciteitsvoorziening (SEV III)",
"Wijziging van de Leegstandwet in verband met de verruiming van de mogelijkheden voor tijdelijke verhuur bij leegstand van gebouwen en woningen",
"Aanpak regeldruk en administratieve lasten",
"Evaluatie Algemene wet gelijke behandeling",
"Beleidsnota Biotechnologie",
"Najaarsnota 2012",
"Preventie en bestrijding van stille armoede en sociale uitsluiting",
"Natuur- en Milieu-educatie",
"Vaststelling van de begrotingsstaten van de begroting Wonen, Wijken en Integratie (XVIII) voor het jaar 2009",
"Politie",
"Vaststelling van de begrotingsstaten van het Ministerie van Volksgezondheid, Welzijn en Sport (XVI) voor het jaar 2016",
"Wijziging van enkele belastingwetten en enkele andere wetten ten behoeve van het afschaffen van de Verklaring arbeidsrelatie (Wet deregulering beoordeling arbeidsrelaties)",
"Wijziging van de begrotingsstaat van het Ministerie van Financiën (IX) voor het jaar 2013 (Incidentele suppletoire begroting DNB winstafdracht)",
"Invoering Diagnose Behandeling Combinaties (DBCs)",
"Vaststelling van de begrotingsstaten van het Ministerie van Volksgezondheid, Welzijn en Sport (XVI) voor het jaar 2014",
"Najaarsnota 2009",
"Vreemdelingenbeleid",
"Geneesmiddelenbeleid",
"Wijziging van enkele belastingwetten en enige andere wetten (Belastingplan 2013)",
"Veteranenzorg",
"Staat van de Europese Unie 2013",
"Preventief gezondheidsbeleid",
"Deelnemingenbeleid Rijksoverheid",
"Wijziging van de Wet personenvervoer 2000 in verband met de invoering van delegatiebepalingen voor de regulering van het systeem van vervoersbewijzen, betaalwijzen en betaaldienstverlening in het openbaar vervoer",
"Parlementair onderzoek Onderhoud en innovatie spoor",
"Vaststelling van de begrotingsstaten van het ministerie van Binnenlandse Zaken en Koninkrijksrelaties (VII) voor het jaar 2012",
"Vaststelling van de begrotingsstaten van het Ministerie van Defensie (X) voor het jaar 2013",
"Evacuatie Nederlandse staatsburger uit Libië",
"Wijziging van de Wet marktordening gezondheidszorg en enkele andere wetten, teneinde te voorkomen dat zorgverzekeraars zelf zorg verlenen of zorg laten aanbieden door zorgaanbieders waarin zij zelf zeggenschap hebben",
"Beleidsbrief Ontwikkelingssamenwerking",
"Jeugdzorg",
"Toekomst AWBZ",
"Hulp, handel en investeringen",
"Handhaving milieuwetgeving",
"Justitiële Inrichtingen",
"Dierproeven",
"Vaststelling van de begrotingsstaten van het Ministerie van Volksgezondheid, Welzijn en Sport (XVI) voor het jaar 2016",
"Vaststelling van de begrotingsstaten van het Ministerie van Volksgezondheid, Welzijn en Sport (XVI) voor het jaar 2009",
"Vreemdelingenbeleid",
"Wijziging van de Wet milieubeheer en de Wet op de economische delicten ten behoeve van de implementatie van richtlijn nr. 2009/29/EG van het Europees Parlement en de Raad van de Europese Unie van 23 april 2009 tot wijziging van Richtlijn 2003/87/EG teneinde de regeling voor de handel in broeikasgasemissierechten binnen de Gemeenschap te verbeteren en uit te breiden (PbEU L 140) en de uitvoering van verordening (EU) nr. 1031/2010 van de Commissie van 12 november 2010 inzake de tijdstippen, het beheer en andere aspecten van de veiling van broeikasgasemissierechten overeenkomstig Richtlijn 2003/87/EG van het Europees Parlement en de Raad tot vaststelling van een regeling voor de handel in broeikasgasemissierechten binnen de Gemeenschap (PbEU L 302) en verordening (EU) nr. 920/2010 van de Commissie van 7 oktober 2010 inzake een gestandaardiseerd en beveiligd registersysteem overeenkomstig Richtlijn 2003/87/EG van het Europees Parlement en de Raad en Beschikking nr. 280/2004/EG van het Europees Parlement en de Raad (PbEU L 270) (herziening EG-richtlijn handel in broeikasgasemissierechten)",
"Dierziektebeleid",
"Het niet indexeren van het basiskinderbijslagbedrag in de Algemene Kinderbijslagwet per 1 juli 2013",
"Wijziging van de Meststoffenwet in verband met de invoering van een stelsel van fosfaatrechten",
"Vaststelling van de begrotingsstaten van het Ministerie van Volksgezondheid, Welzijn en Sport (XVI) voor het jaar 2009",
"Persoonsgebonden Budgetten",
]


