export const partijen = [
"Van Vliet",
"Partij voor de Vrijheid",
"ChristenUnie",
"Groep van Oudenallen",
"Groep De Jong",
"50PLUS",
"Democratisch Politiek Keerpunt",
"Socialistische Partij",
"Brinkman",
"50PLUS/Klein",
"Monasch",
"Staatkundig Gereformeerde Partij",
"Leefbaar Nederland",
"Partij voor de Dieren",
"Groep Eerdmans-van Schijndel",
"Lijst Pim Fortuyn",
"Groep Nawijn",
"DENK",
"Klein",
"50PLUS/Baay-Timmerman",
"Groep Bontes/Van Klaveren",
"Groep Lazrak",
]


export const personen = [
"Sjoera Dikkers",
"Fredrik Teeven",
"Liesbeth Tongeren",
"Selcuk Öztürk",
"Martinus Hendricus Petrus Dam",
"Keklik Yücel",
"H. Backx",
"Gideon Markuszower",
"Foort Oosten van",
"Mevrouw J. Calkoen-Nauta",
"Margot Kraneveldt-van der Veen",
"Helma Neppérus",
"Raymond Knops",
"H. Andela",
"Martine Baay",
"Lilianne Ploumen",
"Antonius Adrianus Gerardus Maria Raak",
"De heer R.A.C. Hoksbergen",
"Antoine Pierre Cornelis Dijck",
"Mark Rutte",
"Jaap Hanekamp",
"E. Ugurlu",
"Sanne Van Eerden",
"Machiel Graaf de",
"Jet Bussemaker",
"André Postema",
]



export const moties = [
"Mariene Strategie voor het Nederlandse deel van de Noordzee",
"Vaststelling van de begrotingsstaten van het Ministerie van Economische Zaken (XIII) voor het jaar 2009",
"Zorg rond zwangerschap en geboorte",
"Wijziging van enkele belastingwetten en enige andere wetten (Fiscale verzamelwet 2015)",
"Maatregelen verkeersveiligheid",
"Derde Structuurschema Elektriciteitsvoorziening (SEV III)",
"Wijziging van de Leegstandwet in verband met de verruiming van de mogelijkheden voor tijdelijke verhuur bij leegstand van gebouwen en woningen",
"Aanpak regeldruk en administratieve lasten",
"Evaluatie Algemene wet gelijke behandeling",
"Beleidsnota Biotechnologie",
"Najaarsnota 2012",
"Preventie en bestrijding van stille armoede en sociale uitsluiting",
"Natuur- en Milieu-educatie",
"Vaststelling van de begrotingsstaten van de begroting Wonen, Wijken en Integratie (XVIII) voor het jaar 2009",
"Politie",
"Vaststelling van de begrotingsstaten van het Ministerie van Volksgezondheid, Welzijn en Sport (XVI) voor het jaar 2016",
"Wijziging van enkele belastingwetten en enkele andere wetten ten behoeve van het afschaffen van de Verklaring arbeidsrelatie (Wet deregulering beoordeling arbeidsrelaties)",
"Wijziging van de begrotingsstaat van het Ministerie van Financiën (IX) voor het jaar 2013 (Incidentele suppletoire begroting DNB winstafdracht)",
"Invoering Diagnose Behandeling Combinaties (DBCs)",
"Vaststelling van de begrotingsstaten van het Ministerie van Volksgezondheid, Welzijn en Sport (XVI) voor het jaar 2014",
"Najaarsnota 2009",
"Vreemdelingenbeleid",
"Geneesmiddelenbeleid",
"Wijziging van enkele belastingwetten en enige andere wetten (Belastingplan 2013)",
"Veteranenzorg",
"Staat van de Europese Unie 2013",
"Preventief gezondheidsbeleid",
"Deelnemingenbeleid Rijksoverheid",
"Wijziging van de Wet personenvervoer 2000 in verband met de invoering van delegatiebepalingen voor de regulering van het systeem van vervoersbewijzen, betaalwijzen en betaaldienstverlening in het openbaar vervoer",
"Parlementair onderzoek Onderhoud en innovatie spoor",
"Vaststelling van de begrotingsstaten van het ministerie van Binnenlandse Zaken en Koninkrijksrelaties (VII) voor het jaar 2012",
"Vaststelling van de begrotingsstaten van het Ministerie van Defensie (X) voor het jaar 2013",
"Evacuatie Nederlandse staatsburger uit Libië",
"Wijziging van de Wet marktordening gezondheidszorg en enkele andere wetten, teneinde te voorkomen dat zorgverzekeraars zelf zorg verlenen of zorg laten aanbieden door zorgaanbieders waarin zij zelf zeggenschap hebben",
"Beleidsbrief Ontwikkelingssamenwerking",
"Jeugdzorg",
"Toekomst AWBZ",
"Hulp, handel en investeringen",
"Handhaving milieuwetgeving",
"Justitiële Inrichtingen",
"Dierproeven",
"Vaststelling van de begrotingsstaten van het Ministerie van Volksgezondheid, Welzijn en Sport (XVI) voor het jaar 2016",
"Vaststelling van de begrotingsstaten van het Ministerie van Volksgezondheid, Welzijn en Sport (XVI) voor het jaar 2009",
"Vreemdelingenbeleid",
"Wijziging van de Wet milieubeheer en de Wet op de economische delicten ten behoeve van de implementatie van richtlijn nr. 2009/29/EG van het Europees Parlement en de Raad van de Europese Unie van 23 april 2009 tot wijziging van Richtlijn 2003/87/EG teneinde de regeling voor de handel in broeikasgasemissierechten binnen de Gemeenschap te verbeteren en uit te breiden (PbEU L 140) en de uitvoering van verordening (EU) nr. 1031/2010 van de Commissie van 12 november 2010 inzake de tijdstippen, het beheer en andere aspecten van de veiling van broeikasgasemissierechten overeenkomstig Richtlijn 2003/87/EG van het Europees Parlement en de Raad tot vaststelling van een regeling voor de handel in broeikasgasemissierechten binnen de Gemeenschap (PbEU L 302) en verordening (EU) nr. 920/2010 van de Commissie van 7 oktober 2010 inzake een gestandaardiseerd en beveiligd registersysteem overeenkomstig Richtlijn 2003/87/EG van het Europees Parlement en de Raad en Beschikking nr. 280/2004/EG van het Europees Parlement en de Raad (PbEU L 270) (herziening EG-richtlijn handel in broeikasgasemissierechten)",
"Dierziektebeleid",
"Het niet indexeren van het basiskinderbijslagbedrag in de Algemene Kinderbijslagwet per 1 juli 2013",
"Wijziging van de Meststoffenwet in verband met de invoering van een stelsel van fosfaatrechten",
"Vaststelling van de begrotingsstaten van het Ministerie van Volksgezondheid, Welzijn en Sport (XVI) voor het jaar 2009",
"Persoonsgebonden Budgetten",
]


export const wetsvoorstellen = [
"Verandering in de Grondwet, strekkende tot het opnemen van een constitutionele basis voor Caribische openbare lichamen en het regelen van een kiescollege voor de Eerste Kamer",
"Intrekking van de Zondagswet en wijziging van de Gemeentewet in verband met de bescherming van sportbeoefening en andere vormen van ontspanning op zondag (Intrekkingswet Zondagswet)",
"Wijziging van de Wet op de inlichtingen- en veiligheidsdiensten 2002 in verband met de invoering van een onafhankelijke bindende toets voorafgaand aan de inzet van bijzondere bevoegdheden jegens journalisten, welke gericht is op het achterhalen van hun bronnen",
"Voorstel van wet van het lid Van Raak tot verandering in de Grondwet, strekkende tot opneming van bepalingen inzake het correctief referendum",
"Voorstel van wet van het lid Jetten houdende verandering in de Grondwet, strekkende tot de deconstitutionalisering van de benoeming van de commissaris van de Koning en de burgemeester",
"Voorstel van wet van de leden Van Raak, Van der Linde, Koolmees, Vermeij, Van Vliet en Van Toorenburg tot wijziging van de Wet op de parlementaire enquête 2008 in verband met de evaluatie van deze wet",
"Wijziging van de begrotingsstaat van het provinciefonds voor het jaar 2017 (wijziging samenhangende met de Voorjaarsnota)",
"Wijziging van de begrotingsstaten van het Ministerie van Binnenlandse Zaken en Koninkrijksrelaties (VII) voor het jaar 2017 (wijziging samenhangende met de Voorjaarsnota)",
"Wijziging van de begrotingsstaat van de Staten-Generaal (IIA) voor het jaar 2017 (wijziging samenhangende met de Voorjaarsnota)",
]


export const landen = [
"Afghanistan",
"ÅLand Islands",
"Albania",
"Algeria",
"American Samoa",
"Andorra",
"Angola",
"Anguilla",
"Antarctica",
"Antigua And Barbuda",
"Argentina",
"Armenia",
"Aruba",
"Australia",
"Austria",
"Azerbaijan",
"Bahamas (The)",
"Bahrain",
"Bangladesh",
"Barbados",
"Belarus",
"Belgium",
"Belize",
"Benin",
"Bermuda",
"Bhutan",
"Bolivia (Plurinational State Of)",
"Bonaire, Saint Eustatius And Saba",
"Bosnia And Herzegovina",
"Botswana",
"Bouvet Island",
"Brazil",
"British Indian Ocean Territory (The)",
"Brunei Darussalam",
"Bulgaria",
"Burkina Faso",
"Burundi",
"Cambodia",
"Cameroon",
"Canada",
"Cape Verde",
"Cayman Islands (The)",
"Central African Republic (The)",
"Chad",
"Chile",
"China",
"Christmas Island",
"Cocos (Keeling) Islands (The)",
"Colombia",
"Comoros (The)",
"Congo (The)",
"Congo, The Democratic Republic Of The",
"Cook Islands (The)",
"Costa Rica",
"CÔTe D'Ivoire",
"Croatia",
"Cuba",
"CuraÇAo",
"Cyprus",
"Czech Republic (The)",
"Denmark",
"Djibouti",
"Dominica",
"Dominican Republic (The)",
"Ecuador",
"Egypt",
"El Salvador",
"Equatorial Guinea",
"Eritrea",
"Estonia",
"Ethiopia",
"Falkland Islands (The) [Malvinas]",
"Faroe Islands (The)",
"Fiji",
"Finland",
"France",
"French Guiana",
"French Polynesia",
"French Southern Territories (The)",
"Gabon",
"Gambia (The)",
"Georgia",
"Germany",
"Ghana",
"Gibraltar",
"Greece",
"Greenland",
"Grenada",
"Guadeloupe",
"Guam",
"Guatemala",
"Guernsey",
"Guinea",
"Guinea-Bissau",
"Guyana",
"Haiti",
"Heard Island And Mcdonald Islands",
"Holy See (The)",
"Honduras",
"Hong Kong",
"Hungary",
"Iceland",
"India",
"Indonesia",
"Iran (Islamic Republic Of)",
"Iraq",
"Ireland",
"Isle Of Man",
"Israel",
"Italy",
"Jamaica",
"Japan",
"Jersey",
"Jordan",
"Kazakhstan",
"Kenya",
"Kiribati",
"Korea (Democratic People'S Republic Of)",
"Korea (Republic Of)",
"Kosovo",
"Kuwait",
"Kyrgyzstan",
"Lao People'S Democratic Republic (The)",
"Latvia",
"Lebanon",
"Lesotho",
"Liberia",
"Libyan Arab Jamahiriya",
"Liechtenstein",
"Lithuania",
"Luxembourg",
"Macao",
"Macedonia (The Former Yugoslav Republic Of)",
"Madagascar",
"Malawi",
"Malaysia",
"Maldives",
"Mali",
"Malta",
"Marshall Islands (The)",
"Martinique",
"Mauritania",
"Mauritius",
"Mayotte",
"Mexico",
"Micronesia (Federated States Of)",
"Moldova (Republic Of)",
"Monaco",
"Mongolia",
"Montenegro",
"Montserrat",
"Morocco",
"Mozambique",
"Myanmar",
"Namibia",
"Nauru",
"Nepal",
"Netherlands (The)",
"Netherland Antilles",
"New Caledonia",
"New Zealand",
"Nicaragua",
"Niger (The)",
"Nigeria",
"Niue",
"Norfolk Island",
"Northern Mariana Islands (The)",
"Norway",
"Oman",
"Pakistan",
"Palau",
"Palestinian Territory, Occupied",
"Panama",
"Papua New Guinea",
"Paraguay",
"Peru",
"Philippines (The)",
"Pitcairn",
"Poland",
"Portugal",
"Puerto Rico",
"Qatar",
"Reunion",
"Romania",
"Russian Federation (The)",
"Rwanda",
"Saint BarthÉLemy",
"Saint Helena, Ascension And Tristan Da Cunha",
"Saint Kitts And Nevis",
"Saint Lucia",
"Saint Martin (French Part)",
"Saint Pierre And Miquelon",
"Saint Vincent And The Grenadines",
"Samoa",
"San Marino",
"Sao Tome And Principe",
"Saudi Arabia",
"Senegal",
"Serbia",
"Seychelles",
"Sierra Leone",
"Singapore",
"Sint Maarten (Dutch Part)",
"Slovakia",
"Slovenia",
"Solomon Islands",
"Somalia",
"South Africa",
"South Georgia And The South Sandwich Islands",
"South Sudan",
"Spain",
"Sri Lanka",
"Sudan (The)",
"Suriname",
"Svalbard And Jan Mayen",
"Swaziland",
"Sweden",
"Switzerland",
"Syrian Arab Republic",
"Taiwan (Province Of China)",
"Tajikistan",
"Tanzania, United Republic Of",
"Thailand",
"Timor-Leste",
"Togo",
"Tokelau",
"Tonga",
"Trinidad And Tobago",
"Tunisia",
"Turkey",
"Turkmenistan",
"Turks And Caicos Islands (The)",
"Tuvalu",
"Uganda",
"Ukraine",
"United Arab Emirates (The)",
"United Kingdom Of Great Britain And Northern Ireland (The)",
"United States Of America (The)",
"United States Minor Outlying Islands (The)",
"Uruguay",
"Uzbekistan",
"Vanuatu",
"Venezuela (Bolivarian Republic Of)",
"Viet Nam",
"Virgin Islands (British)",
"Virgin Islands (U.S.)",
"Wallis And Futuna",
"Western Sahara",
"Yemen",
"Zambia",
"Zimbabwe",
"Former Yugoslavia",
"Ascension Island",
"Tristan da Cunha",
]

export const sector = [
"Education policy and administrative management",
"Education facilities and training",
"Teacher training",
"Educational research",
"Primary education",
"Basic life skills for youth and adults",
"Basic life skills for youth",
"Primary education equivalent for adults",
"Early childhood education",
"Secondary education",
"Lower secondary education",
"Upper secondary education",
"Vocational training",
"Higher education",
"Advanced technical and managerial training",
"Health policy and administrative management",
"Medical education/training",
"Medical research",
"Medical services",
"Basic health care",
"Basic health infrastructure",
"Basic nutrition",
"Infectious disease control",
"Health education",
"Malaria control",
"Tuberculosis control",
"Health personnel development",
"Population policy and administrative management",
"Reproductive health care",
"Family planning",
"STD control including HIV/AIDS",
"Personnel development for population and reproductive health",
"Water sector policy and administrative management",
"Water resources conservation (including data collection)",
"Water supply and sanitation - large systems",
"Water supply - large systems",
"National road construction",
"Sanitation - large systems",
"Basic drinking water supply and basic sanitation",
"Basic drinking water supply",
"Basic sanitation",
"River basins’ development",
"Waste management / disposal",
"Education and training in water supply and sanitation",
"Public sector policy and administrative management",
"Public finance management",
"Decentralisation and support to subnational government",
"Anti-corruption organisations and institutions",
"Tax policy and tax administration support",
"Tax collection",
"Budget planning",
"National audit",
"Debt and aid management",
"Public sector financial management",
"Foreign affairs",
"Diplomatic missions",
"Administration of developing countries' foreign aid",
"General personnel services",
"Central procurement",
"Other general public services",
"National monitoring and evaluation",
"Local government finance",
"Other central transfers to institutions",
"Security system management and reform",
"National road maintenance",
"Legal and judicial development",
"Justice, law and order policy, planning and administration",
"Police",
"Fire and rescue services",
"Judicial affairs",
"Ombudsman",
"Immigration",
"Prisons",
"Government administration",
"Macroeconomic policy",
"Meteorological services",
"National standards development",
"Democratic participation and civil society",
"Elections",
"Legislatures and political parties",
"Media and free flow of information",
"Executive office",
"Tax policy and administration support",
"Other non-tax revenue mobilisation",
"Human rights",
"Elections",
"Human rights",
"Free flow of information",
"Women's equality organisations and institutions",
"Women’s equality organisations and institutions",
"Local government administration",
"Feeder road construction",
"Feeder road maintenance",
"Civilian peace-building, conflict prevention and resolution",
"Participation in international peacekeeping operations",
"Reintegration and SALW control",
"Removal of land mines and explosive remnants of war",
"Child soldiers (Prevention and demobilisation)",
"Social/ welfare services",
"Social protection and welfare services policy, planning and administration",
"Social security (excl pensions)",
"General pensions",
"Civil service pensions",
"Social services (incl youth development and women+ children)",
"Employment policy and administrative management",
"Housing policy and administrative management",
"Low-cost housing",
"Multisector aid for basic social services",
"Culture and recreation",
"Statistical capacity building",
"Narcotics control",
"Social mitigation of HIV/AIDS",
"Recreation and sport",
"Culture",
"Transport policy and administrative management",
"Transport policy, planning and administration",
"Public transport services",
"Transport regulation",
"Road transport",
"Rail transport",
"Water transport",
"Air transport",
"Storage",
"Education and training in transport and storage",
"Communications policy and administrative management",
"Communications policy, planning and administration",
"Postal services",
"Information services",
"Telecommunications",
"Radio/television/print media",
"Information and communication technology (ICT)",
"Energy policy and administrative management",
"Power generation/non-renewable sources",
"Power generation/renewable sources",
"Electrical transmission/ distribution",
"Gas distribution",
"Oil-fired power plants",
"Gas-fired power plants",
"Coal-fired power plants",
"Nuclear power plants",
"Hydro-electric power plants",
"Geothermal energy",
"Solar energy",
"Wind power",
"Ocean power",
"Biomass",
"Energy education/training",
"Energy research",
"Financial policy and administrative management",
"Monetary institutions",
"Formal sector financial intermediaries",
"Informal/semi-formal financial intermediaries",
"Education/training in banking and financial services",
"Business support services and institutions",
"Privatisation",
"Agricultural policy and administrative management",
"Agricultural development",
"Agricultural land resources",
"Agricultural water resources",
"Agricultural inputs",
"Food crop production",
"Industrial crops/export crops",
"Livestock",
"Agrarian reform",
"Agricultural alternative development",
"Agricultural extension",
"Agricultural education/training",
"Agricultural research",
"Agricultural services",
"Plant and post-harvest protection and pest control",
"Agricultural financial services",
"Agricultural co-operatives",
"Livestock/veterinary services",
"Forestry policy and administrative management",
"Forestry development",
"Fuelwood/charcoal",
"Forestry education/training",
"Forestry research",
"Forestry services",
"Fishing policy and administrative management",
"Fishery development",
"Fishery education/training",
"Fishery research",
"Fishery services",
"Industrial policy and administrative management",
"Industrial development",
"Small and medium-sized enterprises (SME) development",
"Cottage industries and handicraft",
"Agro-industries",
"Forest industries",
"Textiles, leather and substitutes",
"Chemicals",
"Fertilizer plants",
"Cement/lime/plaster",
"Energy manufacturing",
"Pharmaceutical production",
"Basic metal industries",
"Non-ferrous metal industries",
"Engineering",
"Transport equipment industry",
"Technological research and development",
"Mineral/mining policy and administrative management",
"Mineral prospection and exploration",
"Coal",
"Oil and gas",
"Ferrous metals",
"Nonferrous metals",
"Precious metals/materials",
"Industrial minerals",
"Fertilizer minerals",
"Offshore minerals",
"Construction policy and administrative management",
"Trade policy and administrative management",
"Trade facilitation",
"Regional trade agreements (RTAs)",
"Multilateral trade negotiations",
"Trade-related adjustment",
"Trade education/training",
"Tourism policy and administrative management",
"Environmental policy and administrative management",
"Biosphere protection",
"Bio-diversity",
"Site preservation",
"Flood prevention/control",
"Environmental education/ training",
"Environmental research",
"Multisector aid",
"Urban development and management",
"Urban land policy and management",
"Urban development",
"Rural development",
"Rural land policy and management",
"Rural development",
"Non-agricultural alternative development",
"Multisector education/training",
"Research/scientific institutions",
"General budget support",
"Food aid/Food security programmes",
"Import support (capital goods)",
"Import support (commodities)",
"Action relating to debt",
"Debt forgiveness",
"Relief of multilateral debt",
"Rescheduling and refinancing",
"Debt for development swap",
"Other debt swap",
"Debt buy-back",
"Material relief assistance and services",
"Emergency food aid",
"Relief co-ordination; protection and support services",
"Reconstruction relief and rehabilitation",
"Disaster prevention and preparedness",
"Administrative costs",
"Support to national NGOs",
"Support to international NGOs",
"Support to local and regional NGOs",
"Refugees in donor countries",
"Sectors not specified",
"Promotion of development awareness",
"Solar energy",
"Heat plants",
"Coal-fired electric power plants",
"Nuclear energy electric power plants",
"Energy policy and administrative management",
"Energy sector policy, planning and administration",
"Energy regulation",
"Ending violence against women and girls ",
"Marine energy",
"Hybrid energy electric power plants",
"Wind energy",
"Energy generation, non-renewable sources – unspecified",
"Gas distribution",
"Oil-fired electric power plants",
"Energy conservation and demand-side efficiency",
"Energy education/training",
"Geothermal energy",
"Energy research",
"Natural gas-fired electric power plants",
"Hydro-electric power plants",
"Electric power transmission and distribution",
"Non-renewable waste-fired electric power plants",
"Energy generation, renewable sources – multiple technologies",
"Fossil fuel electric power plants with carbon capture and storage (CCS)",
"District heating and cooling",
"Biofuel-fired power plants",
]


export default {
    partijen,
    personen,
    moties,
    wetsvoorstellen,
    landen,
    sector,
}
